### ISSUE TITLE
Drag & Drop

### ISSUE THREAD

**Issue by MM-Mikhail** [chris-y/avalanche#80]
Would be nice to see D&D work, so you can drop a file on a window to get it listed without going through the file selection that could be more difficult if the file is already on desktop..

**Comment by MM-Mikhail** [comment]
Update:  It actually works!!!  But only if running on WB and it's the first thing you do.

It does not work in DOpus5, and it does not work in WB either after Dopus5 was run and quit.
Very odd.


Another issue is the cannot open file requester (eg, drop an exe file)
This req gets displayed 1 sec (at most) and gets put away behind the main window.and you are viewing a stuck interface wondering what;s up ?
The req should be brought upfront for the user to see, and if user clicks main window that is locked, maybe move the req upfront.

**Comment by chris-y** [comment]
Weird. This was happening to me but I fixed it in 3.1 (or at least I thought I had).

**Comment by chris-y** [comment]
I can't reproduce either of these with v3.1.

Which version of the OS are you using?  I'm testing here with a fairly basic install of 3.2.3.

**Comment by MM-Mikhail** [comment]
My description was not complete

Open Avalnche, select any program icon and drop it on the window to get the error
The req will be hidden behind (all centred on screen)

DOpus runs in parallel or can be a WB replacement, or a visitor on WB screen.
Other apps do the D&D trick somehow different I guess since all work fine and this is the first app that shows such unusual behaviour.

**Comment by chris-y** [comment]
That's what I tried.  The requester comes up in front as expected.

The usual drag'n'drop I did see that issue (only the first drop was working), but I fixed that in 3.1.  I'm not sure whether it was working previously or I broke it during the 3.1 updates.

It's entirely possible there's another bug there which means it is only working here by accident.  That will be quite tricky to track down though.

There's nothing particularly odd about how I do it - just make the window an AppWindow and add DropZones for the whole window and for the listview area.  I do have only one DropZone sometimes and add/remove it to prevent drop events.  I could try changing it so it ignores drop events rather than removing the dropzone, in case the remove/add is causing problems?

**Comment by MM-Mikhail** [comment]
No, no changes.

Error window can still popup and go behind the main window.
The moment DOpus5 is activated, D&D refuses to work from WB or DOpus.

New problem.  When it works, under WB only, dropping a few bad files in a row caused it to crash softly, that is you can continue to drop icons into the window, it will show the path of the archive, but nothing is updated in the main view, stay empty.

**Comment by chris-y** [comment]
Interesting, thanks

**Comment by chris-y** [comment]
Fab!

I'll have a look at the error request next, and see if I can reproduce that soft-crash.

Have a look at #18 for iconification icons (or at least comment there - might prompt me to do something about it)

**Comment by MM-Mikhail** [comment]
No, 2 problems still remain.

1. Drop an image file, get an error message, requester moved behind main window, or main window is moved upfront covering the error and thus blocking input, until you find the error window and close it.
2. Same with the soft crash, keep dropping image, different archive types, opening a file with a req, and after a few times, the content window will stop updating.
